#ifndef ASMOFFSETS_H
#define ASMOFFSETS_H
#define OFFSETOF_DCB_DISP	0
#define OFFSETOF_DCB_DISABLED	4
#define OFFSETOF_DCB_VSPACE	8
#define OFFSETOF_DCB_RBED_NEXT	40
#define OFFSETOF_DISP_DISABLED	0
#define OFFSETOF_DISP_RUN	24
#define OFFSETOF_DISP_LRPC	28
#define OFFSETOF_DISP_UDISP	8
#define OFFSETOF_DISP_LMP_DELIVERED	12
#define OFFSETOF_DISP_SYSTIME	48
#define OFFSETOF_DISP_PRIV_STACK_LIMIT	12800
#define OFFSETOF_DISP_PRIV_TRAP_STACK_LIMIT	6400
#define OFFSETOF_DISP_SAVE_AREA	92
#define OFFSETOF_DISP_GENERIC	160
#define SYS_ERR_OK	0
#define SYS_ERR_LMP_TARGET_DISABLED	10
#define SYS_ERR_LMP_BUF_OVERFLOW	11
#define SYS_ERR_LRPC_SLOT_INVALID	17
#define SYS_ERR_LRPC_NOT_ENDPOINT	18
#define SIZEOF_STRUCT_SYSRET	8
#endif /* ASMOFFSETS_H */
